export type AgaDetector = {
  id: string;
  tag: string | null;
  abb_tagname: string | null;
  description: string | null;
  recipe: string | null;
  rgu: string | null;
  area: string | null;
  system_status: string | null;
  field_status: string | null;
  unit_serial: string | null;
  calibration_date: string | null;
  calibration_due_date: string | null;
  serial_no_detector: string | null;
  serial_no_sensor: string | null;
  location: string | null;
  media: string | null;
  sensor_change: string | null;
  calibration_gas: string | null;
  range_min: number | null;
  range_max: number | null;
  unit: string | null;
  accuracy: string | null;
  trip_point_h: string | null;
  trip_point_hh: string | null;
  zero_gas_cert: string | null;
  span_gas_cert: string | null;
  o_adjust: string | null;
  span_adjust: string | null;
  iq_reprogrammed: string | null;
  remarks: string | null;
  nne_remarks: string | null;
  created_at: string;
  updated_at: string;
};
